### Obtener todos los libros
GET http://localhost:5000/libros
Accept: application/json

### Crear un nuevo libro
POST http://localhost:5000/libros
Content-Type: application/json

{
  "titulo": "Cien años de soledad",
  "autor": "Gabriel García Márquez",
  "anho": 1967,
  "isbn": "9780307474728"
}

### Obtener un libro por id
GET http://localhost:5000/libros/1
Accept: application/json

### Modificar un libro por id
PUT http://localhost:5000/libros/1
Content-Type: application/json

{
  "titulo": "Cien años de soledad (Edición revisada)",
  "autor": "Gabriel García Márquez",
  "anho": 1967,
  "isbn": "9780307474728"
}

### Eliminar un libro por id
DELETE http://localhost:5000/libros/1
